# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AlgoAll_cpp <- function(X, Fm, Gm, L, Linv, Dinv, K, R, niter, swipes = 10L, threshold = 0.01, nugget = 1e-9, upd_row = "C", upd_col = "S") {
    .Call(`_TRIFASE_AlgoAll_cpp`, X, Fm, Gm, L, Linv, Dinv, K, R, niter, swipes, threshold, nugget, upd_row, upd_col)
}

Algo4_cpp <- function(X, Fm, Gm, L, Linv, Dinv, K, R, niter, swipes = 10L, threshold = 0.01, nugget = 1e-9, stoc = TRUE) {
    .Call(`_TRIFASE_Algo4_cpp`, X, Fm, Gm, L, Linv, Dinv, K, R, niter, swipes, threshold, nugget, stoc)
}

aa <- function(x) {
    .Call(`_TRIFASE_aa`, x)
}

AlgoAll_cpp2 <- function(X, Fm, Gm, L, iKernel, current_tau, Linv, Dinv, K, R, niter, swipes = 10L, threshold = 0.01, nugget = 1e-9, estimate_tau = TRUE, upd_row = "C", upd_col = "S") {
    .Call(`_TRIFASE_AlgoAll_cpp2`, X, Fm, Gm, L, iKernel, current_tau, Linv, Dinv, K, R, niter, swipes, threshold, nugget, estimate_tau, upd_row, upd_col)
}

